### ISSUE TITLE
IntelliSense has some issues with "selected item"

### ISSUE THREAD

**Issue by HDenizD** [ergenekonyigit/real-github-dark-theme#4]
Bro, u did a awesome job with this theme. But there is a small thing which makes the usage of IntelliSense a slightly hard.

When using autocomplete you can't really see which item u have selected, :hover is good but :focus (arrow keys selecting) needs the active marker for each item as well.

Please check my GIF
![JW8zthgL39](https://user-images.githubusercontent.com/27643142/108607160-fcf7a280-73be-11eb-9dbb-8bdea5372605.gif)

**Comment by ergenekonyigit** [comment]
hi, this project just fork of official github theme v2. I will archive this project after merging this pr https://github.com/primer/github-vscode-theme/pull/132
